development:
  adapter: oracle_enhanced
  database: ADB
  username: jal2238
  password: realmadrid
  pool: 5
  timeout: 5000

test:
  adapter: oracle_enhanced
  database: ADB
  username: jal2238
  password: realmadrid
  pool: 5
  timeout: 5000

production:
  adapter: oracle_enhanced
  database: ADB
  username: jal2238
  password: realmadrid
  pool: 5
  timeout: 5000
